In [1]:

# This notebook was created to split the AML dataset in 5 Folds for train, test and val 
# Environment: Aixa_ARMED_2
import anndata
from scMEDAL.utils.splitter import DataSplitter
from scMEDAL.utils.utils import read_adata
from config_split_paths import data_path,data2split_foldername,folder_splits
import numpy as np

data_base_path: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/scMEDAL_for_scRNAseq/Experiments/AML/../data/AML_data
outputs_path: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/scMEDAL_for_scRNAseq/Experiments/AML/../outputs/AML_outputs

In [2]:
adata2split_path = data_path + "/" + data2split_foldername
print(adata2split_path)
X,var,obs = read_adata(adata2split_path, issparse=False)
adata = anndata.AnnData(X,obs=obs,var=var)

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/scMEDAL_for_scRNAseq/Experiments/AML/../data/AML_data/log_transformed_2916hvggenes
Reading data from: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/scMEDAL_for_scRNAseq/Experiments/AML/../data/AML_data/log_transformed_2916hvggenes

/project/bioinformatics/DLLab/shared/CondaEnvironments/Aixa_ARMED_2/lib/python3.8/site-packages/anndata/_core/anndata.py:119: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

In [3]:
adata.obs

,Unnamed: 0,Unnamed: 0.1,Cell,NumberOfReads,AlignedToGenome,AlignedToTranscriptome,TranscriptomeUMIs,NumberOfGenes,CyclingScore,CyclingBinary,...,Score_CTL,Score_NK,NanoporeTranscripts,id,Day,unique_id,Patient_group,celltype,batch,n_genes
0,0,0,AML328-D0_AAAAACAGAAGT,24994,15391,7477,1236,581,-0.351,no,...,0.184,0.447,NaN,AML328,D0,AML328_D0,AML,NK,AML328,581
1,1,1,AML328-D0_AAAACCGCTACT,55122,34633,17252,3394,1238,-0.409,no,...,0.052,0.037,NaN,AML328,D0,AML328_D0,AML,HSC-like,AML328,1238
2,2,2,AML328-D0_AAAACCGGCTTT,43393,26813,16148,2649,1243,-0.401,no,...,0.032,0.034,NaN,AML328,D0,AML328_D0,AML,Prog-like,AML328,1243
3,3,3,AML328-D0_AAAAGCTTATCA,25085,15404,9483,1582,633,-0.378,no,...,0.167,0.080,NaN,AML328,D0,AML328_D0,AML,T,AML328,633
4,4,4,AML328-D0_AAAAGTCCCCGT,54911,33226,20545,3280,1376,-0.629,no,...,0.010,0.009,NaN,AML328,D0,AML328_D0,AML,Mono-like,AML328,1376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38412,41085,41085,AML328-D171_CCATCATCCACC,26414,19298,13674,2516,939,-0.257,no,...,0.135,0.109,NaN,AML328,D171,AML328_D171,AML,T,AML328,939
38413,41086,41086,AML328-D171_TTTTATCATTCT,27460,20073,9433,1651,878,-0.524,no,...,0.226,0.213,NaN,AML328,D171,AML328_D171,AML,T,AML328,878
38414,41087,41087,AML328-D171_AAGATGTAGCGT,12394,8787,6543,1331,504,-0.348,no,...,0.074,0.041,NaN,AML328,D171,AML328_D171,AML,HSC,AML328,504
38415,41088,41088,AML328-D171_CTGTAGCTCCTA,19172,13904,10351,1792,745,-0.394,no,...,0.045,0.052,NaN,AML328,D171,AML328_D171,AML,Prog-like,AML328,745
38416,41089,41089,AML328-D171_GATTTGGACGTT,15912,11652,6120,1153,580,-0.310,no,...,0.138,0.067,NaN,AML328,D171,AML328_D171,AML,T,AML328,580

In [4]:
len(np.unique(adata.obs["batch"]))

19

In [5]:
adata.obs['celltype'] = adata.obs['celltype'].astype('category')
adata.obs['batch'] = adata.obs["batch"].astype('category')

In [6]:
#Check data to split
print("count matrix shape:",adata.shape)
print("n cell types:",len(np.unique(adata.obs["celltype"])))
print("cell types:",np.unique(adata.obs["celltype"]))
print("\nn batches:",len(np.unique(adata.obs["batch"])))
print("batches:",np.unique(adata.obs["batch"]))

count matrix shape: (38417, 2916)
n cell types: 21
cell types: ['B' 'CTL' 'GMP' 'GMP-like' 'HSC' 'HSC-like' 'Mono' 'Mono-like' 'NK'
 'Plasma' 'ProB' 'ProMono' 'ProMono-like' 'Prog' 'Prog-like' 'T' 'cDC'
 'cDC-like' 'earlyEry' 'lateEry' 'pDC']

n batches: 19
batches: ['AML1012' 'AML210A' 'AML328' 'AML329' 'AML419A' 'AML420B' 'AML475'
 'AML556' 'AML707B' 'AML870' 'AML916' 'AML921A' 'BM1' 'BM2' 'BM3' 'BM4'
 'BM5' 'MUTZ3' 'OCI']

In [7]:
adata.var

,Unnamed: 0,Unnamed: 0.1,Gene,n_cells,highly_variable,means,dispersions,dispersions_norm
0,3,3,A2M,471,True,0.077933,2.261810,1.592536
1,4,4,A2M-AS1,213,True,0.029655,2.163001,1.239412
2,32,32,AASDH,2140,True,0.215799,2.052757,0.845417
3,41,41,ABCA1,988,True,0.120652,2.033437,0.776373
4,50,50,ABCA5,1478,True,0.189636,2.228214,1.472471
...,...,...,...,...,...,...,...,...
2911,27860,27860,ZSCAN16,607,True,0.067904,2.110978,1.053490
2912,27880,27880,ZSWIM3,170,True,0.018544,2.065729,0.891779
2913,27882,27882,ZSWIM5,71,True,0.010590,2.033077,0.775084
2914,27887,27887,ZUFSP,1813,True,0.184481,2.074728,0.923939
2915,27897,27897,ZZEF1,2526,True,0.276250,2.014677,0.709326

In [8]:
adata.obs.head(5)

,Unnamed: 0,Unnamed: 0.1,Cell,NumberOfReads,AlignedToGenome,AlignedToTranscriptome,TranscriptomeUMIs,NumberOfGenes,CyclingScore,CyclingBinary,...,Score_CTL,Score_NK,NanoporeTranscripts,id,Day,unique_id,Patient_group,celltype,batch,n_genes
0,0,0,AML328-D0_AAAAACAGAAGT,24994,15391,7477,1236,581,-0.351,no,...,0.184,0.447,NaN,AML328,D0,AML328_D0,AML,NK,AML328,581
1,1,1,AML328-D0_AAAACCGCTACT,55122,34633,17252,3394,1238,-0.409,no,...,0.052,0.037,NaN,AML328,D0,AML328_D0,AML,HSC-like,AML328,1238
2,2,2,AML328-D0_AAAACCGGCTTT,43393,26813,16148,2649,1243,-0.401,no,...,0.032,0.034,NaN,AML328,D0,AML328_D0,AML,Prog-like,AML328,1243
3,3,3,AML328-D0_AAAAGCTTATCA,25085,15404,9483,1582,633,-0.378,no,...,0.167,0.080,NaN,AML328,D0,AML328_D0,AML,T,AML328,633
4,4,4,AML328-D0_AAAAGTCCCCGT,54911,33226,20545,3280,1376,-0.629,no,...,0.010,0.009,NaN,AML328,D0,AML328_D0,AML,Mono-like,AML328,1376

In [11]:
# Call DataSplitter (5 folds)
splitter = DataSplitter()
# For the Leukemia datase, we will take all donors as seen
DataSplitter.Get_Kfolds_likeAlbert(adata = adata, out_folder=data_path+"/"+folder_splits, n_splits=5, stratified=True, stratify_cols=['batch','celltype'])

/project/bioinformatics/DLLab/shared/CondaEnvironments/Aixa_ARMED_2/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"

Processing Fold 1
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_1/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_1/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_1/val

Processing Fold 2
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_2/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_2/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_2/val

Processing Fold 3
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_3/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_3/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_3/val

Processing Fold 4
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_4/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_4/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_4/val

Processing Fold 5
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_5/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_5/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/VanGallen_2019/log_transformed_2916hvggenes/splits/split_5/val