In [1]:
# This notebook was created to split the ASD dataset in 5 Folds for train, test and val 
# Environment: Aixa_ARMED_2

import anndata
from scMEDAL.utils.splitter import DataSplitter
from scMEDAL.utils.utils import read_adata
from config_split_paths import data_path,data2split_foldername,folder_splits
import numpy as np
import os

In [2]:
# Read data
adata2split_path = os.path.join(data_path,data2split_foldername)
print(adata2split_path)
X,var,obs = read_adata(adata2split_path, issparse=False)
#adata = anndata.AnnData(X,obs=obs,var=var)
#print("adata shape",adata.shape)

/archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes

In [3]:
#X = loaded_X.item()
adata = anndata.AnnData(X,obs=obs,var=var)

/project/bioinformatics/DLLab/shared/CondaEnvironments/Aixa_ARMED_2/lib/python3.8/site-packages/anndata/_core/anndata.py:119: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

In [4]:
adata.obs

,Unnamed: 0,cell,cluster,sample,individual,region,age,sex,diagnosis,Capbatch,...,post-mortem interval (hours),RNA Integrity Number,genes,UMIs,RNA mitochondr. percent,RNA ribosomal percent,celltype,donor,batch,n_genes
0,0,AAACCTGGTACGCACC-1_1823_BA24,Neu-NRGN-II,1823_BA24,1823,ACC,15,M,Control,CB8,...,18,7.0,622,774,2.454780,1.421189,Neu-NRGN-II,donor_1823,donor_1823,622
1,1,AAACGGGCACCAGATT-1_1823_BA24,L5/6,1823_BA24,1823,ACC,15,M,Control,CB8,...,18,7.0,6926,24042,0.445055,0.428417,L5/6,donor_1823,donor_1823,6926
2,2,AAAGATGAGTCCAGGA-1_1823_BA24,Oligodendrocytes,1823_BA24,1823,ACC,15,M,Control,CB8,...,18,7.0,624,830,0.240964,0.722892,Oligodendrocytes,donor_1823,donor_1823,624
3,3,AAAGATGTCTTGAGGT-1_1823_BA24,OPC,1823_BA24,1823,ACC,15,M,Control,CB8,...,18,7.0,1192,1771,0.225861,1.806889,OPC,donor_1823,donor_1823,1192
4,4,AAAGCAAGTAATCACC-1_1823_BA24,Oligodendrocytes,1823_BA24,1823,ACC,15,M,Control,CB8,...,18,7.0,691,895,0.558659,0.670391,Oligodendrocytes,donor_1823,donor_1823,691
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104554,104554,TTTGTCACAAAGTCAA-1_6033_BA9,L5/6,6033_BA9,6033,PFC,14,F,ASD,CB7,...,25,8.0,4555,10514,2.805783,1.245958,L5/6,donor_6033,donor_6033,4554
104555,104555,TTTGTCACAAGGCTCC-1_6033_BA9,OPC,6033_BA9,6033,PFC,14,F,ASD,CB7,...,25,8.0,913,1276,0.156740,0.548589,OPC,donor_6033,donor_6033,913
104556,104556,TTTGTCAGTCGATTGT-1_6033_BA9,Neu-mat,6033_BA9,6033,PFC,14,F,ASD,CB7,...,25,8.0,1807,2874,0.591510,0.765484,Neu-mat,donor_6033,donor_6033,1807
104557,104557,TTTGTCATCCCAAGTA-1_6033_BA9,IN-SV2C,6033_BA9,6033,PFC,14,F,ASD,CB7,...,25,8.0,1451,2185,1.922197,0.320366,IN-SV2C,donor_6033,donor_6033,1451
104558,104558,TTTGTCATCGTTACGA-1_6033_BA9,OPC,6033_BA9,6033,PFC,14,F,ASD,CB7,...,25,8.0,1119,1682,0.178359,0.832342,OPC,donor_6033,donor_6033,1119

In [5]:
len(np.unique(adata.obs["batch"]))

31

In [6]:
adata.obs['celltype'] = adata.obs['celltype'].astype('category')
adata.obs['batch'] = adata.obs["batch"].astype('category')

In [7]:
#Check data to split
print("count matrix shape:",adata.shape)
print("n cell types:",len(np.unique(adata.obs["celltype"])))
print("cell types:",np.unique(adata.obs["celltype"]))
print("\nn batches:",len(np.unique(adata.obs["batch"])))
print("batches:",np.unique(adata.obs["batch"]))

count matrix shape: (104559, 2916)
n cell types: 17
cell types: ['AST-FB' 'AST-PP' 'Endothelial' 'IN-PV' 'IN-SST' 'IN-SV2C' 'IN-VIP'
 'L2/3' 'L4' 'L5/6' 'L5/6-CC' 'Microglia' 'Neu-NRGN-I' 'Neu-NRGN-II'
 'Neu-mat' 'OPC' 'Oligodendrocytes']

n batches: 31
batches: ['donor_1823' 'donor_4341' 'donor_4849' 'donor_4899' 'donor_5144'
 'donor_5163' 'donor_5242' 'donor_5278' 'donor_5294' 'donor_5387'
 'donor_5391' 'donor_5403' 'donor_5408' 'donor_5419' 'donor_5531'
 'donor_5538' 'donor_5554' 'donor_5565' 'donor_5577' 'donor_5841'
 'donor_5864' 'donor_5879' 'donor_5893' 'donor_5936' 'donor_5939'
 'donor_5945' 'donor_5958' 'donor_5976' 'donor_5978' 'donor_6032'
 'donor_6033']

In [8]:
adata.var

,Unnamed: 0,gene_ids,n_cells,highly_variable,means,dispersions,dispersions_norm
0,ENSG00000225972|MTND1P23,ENSG00000225972|MTND1P23,9182,True,0.342605,2.496032,2.354510
1,ENSG00000225630|MTND2P28,ENSG00000225630|MTND2P28,8016,True,0.293084,2.372869,1.576230
2,ENSG00000237973|RP5-857K21.6,ENSG00000237973|RP5-857K21.6,7242,True,0.380024,2.805272,3.612908
3,ENSG00000240409|MTATP8P1,ENSG00000240409|MTATP8P1,6,True,0.000234,2.410808,1.657013
4,ENSG00000224956|RP11-206L10.1,ENSG00000224956|RP11-206L10.1,6,True,0.000193,2.359824,1.548453
...,...,...,...,...,...,...,...
2911,ENSG00000142173|COL6A2,ENSG00000142173|COL6A2,1287,True,0.046377,2.208696,1.226656
2912,ENSG00000160307|S100B,ENSG00000160307|S100B,11734,True,0.594560,2.431238,2.090842
2913,ENSG00000210117|MT-TW,ENSG00000210117|MT-TW,17,True,0.000691,2.268422,1.353830
2914,ENSG00000210156|MT-TK,ENSG00000210156|MT-TK,162,True,0.005567,2.164285,1.132092
2915,ENSG00000210176|MT-TH,ENSG00000210176|MT-TH,27,True,0.000856,2.163577,1.130584

In [10]:
adata.obs.head(5)

,Unnamed: 0,Age,AgeBin,DeathType,DonorID,Gender,Organ,Race,SampleType,Source,Tissue,TissueDetail,_index,celltype,protocol,sampleID,n_genes,batch
0,0,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCAAGAACGCGT-1-H0015_apex',Smooth_muscle_cells,10X3'V3,H0015_apex,480,H0015_apex
1,1,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCAAGCAAACAT-1-H0015_apex',Ventricular_Cardiomyocyte,10X3'V3,H0015_apex,1365,H0015_apex
2,2,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCAAGCTACTGT-1-H0015_apex',Ventricular_Cardiomyocyte,10X3'V3,H0015_apex,1521,H0015_apex
3,3,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCAGTACCGCGT-1-H0015_apex',Pericytes,10X3'V3,H0015_apex,726,H0015_apex
4,4,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCATCAAACCCA-1-H0015_apex',Ventricular_Cardiomyocyte,10X3'V3,H0015_apex,1584,H0015_apex

In [9]:
# Call DataSplitter (5 folds)
splitter = DataSplitter()
DataSplitter.Get_Kfolds_likeAlbert(adata = adata, out_folder=data_path+"/"+folder_splits, n_splits=5, stratified=True, stratify_cols=['batch','celltype'])

/project/bioinformatics/DLLab/shared/CondaEnvironments/Aixa_ARMED_2/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"

Processing Fold 1
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_1/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_1/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_1/val

Processing Fold 2
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_2/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_2/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_2/val

Processing Fold 3
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_3/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_3/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_3/val

Processing Fold 4
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_4/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_4/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_4/val

Processing Fold 5
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_5/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_5/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/ASD/reverse_norm/log_transformed_2916hvggenes/splits/split_5/val

In [8]:
2

2