In [1]:

import os
# Make sure you are in scMEDAL_for_scRNAseq dir
os.chdir("/archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/dev2/scMEDAL_for_scRNAseq")

from models.models import train_model_on_named_experiment

OUTPUTS_DIR: /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/dev2/scMEDAL_for_scRNAseq/outputs

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning:

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP).

For more information see: https://github.com/tensorflow/addons/issues/2807

  warnings.warn(
WARNING:absl:`lr` is deprecated in Keras optimizer, please use `learning_rate` or use the legacy optimizer, e.g.,tf.keras.optimizers.legacy.Adam.
WARNING:absl:`lr` is deprecated in Keras optimizer, please use `learning_rate` or use the legacy optimizer, e.g.,tf.keras.optimizers.legacy.Adam.
WARNING:absl:`lr` is deprecated in Keras optimizer, please use `learning_rate` or use the legacy optimizer, e.g.,tf.keras.optimizers.legacy.Adam.

In [3]:

os.getcwd()

'/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq'

## Training Models:

#### Implemented Models:
| Model Class | Model Description | 
|------------|--------------------|  
| `AE` | Autoencoder | 
| `AEC`| Autoencoder Classifier |
| `scMEDAL-FE` | Domain Adversarial Autoencoder |
| `scMEDAL-FEC`| Domain Adversarial Autoencoder Classifier |
| `scMEDAL-RE`| Domain Enhancing Autoencoder Classifier | 

#### Named Experiments:
| Valid Named Experiment | Dataset |  n_clusters | n_pred |
|------------------------|---------|-------------|--------|
| `AML`| Acute Myeloid Leukemia | 19 | 21 |
| `ASD`| Autism Spectrum Disorder | 31 | 17 | 
| `HH` | Healthy Heart | 147 | 13 | 

**Note:** If training on other datasets, the configs will need to be passed in as dictionaries to `model_kwargs` and `train_kwargs`.

`quick` is a boolean flag that can be passed to `train_kwargs` which shortens training to only 1 fold for 3 epochs.

Run models on all 3 datasets with

$python\ run\_scMEDAL\_alldatasets.py$

## Analyzing Models:

When you run a model, it generates the following output directories:
   - /outputs/figures
   - /outputs/latent_space
   - /outputs/saved_models
 
 Inside each of these directories, there is a subdirectory named after the model and its run identifier.
 
 For example: $ASD/latent\_space/scmedalfe/run\_crossval\_<run\_name>$

 To analyze your results, copy the corresponding $<run\_name>$ below.

In [2]:

# When you run your model, it outputs the figures, latent_space and saved_models directories, whitin those directories you will find a subdir with the name of the model trained, example: AML/latent_space/scmedalfe/run_crossval_<run_name>
# Please copy the <run_name below> to analyze the results
# Update output paths of the models that you just run

from utils.defaults import ASD_OUTPUTS_DIR,ASD_EXPERIMENT_NAME
print(f"Loading outputs from {ASD_OUTPUTS_DIR}. Please verify that your models output folder is located here before proceeding with the analysis.")
import os
model_folder_dict = {
    "ae":"run_crossval_n_latent_dims-50_layer_units-512-132_use_batch_norm-True_scaling-min_max_model_type-ae_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_n_components-50_get_cf_batch-False_2025-07-10_03-10",
    "aec":"run_crossval_n_latent_dims-50_layer_units-512-132_n_pred-17_use_batch_norm-True_scaling-min_max_model_type-aec_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_get_cf_batch-False_2025-07-10_05-16",
    "scmedalfe":"run_crossval_loss_gen_weight-1_loss_recon_weight-1000_loss_class_weight-1_n_latent_dims-50_layer_units-512-132_scaling-min_max_model_type-scmedalfe_batch_size-512_epochs-500_patience-30_sample_size-10000_2025-07-09_22-12",
    "scmedalfec":"run_crossval_loss_gen_weight-1_loss_recon_weight-2000_loss_class_weight-1_n_latent_dims-50_layer_units-512-132_scaling-min_max_model_type-scmedalfec_batch_size-512_epochs-500_patience-30_sample_size-10000_get_cf_batch-False_2025-07-10_00-42",
    "scmedalre":"run_crossval_loss_recon_weight-110_loss_latent_cluster_weight-0.1_n_latent_dims-50_layer_units-512-132_scaling-min_max_batch_size-512_epochs-500_patience-30_sample_size-10000_2025-07-10_07-53",
    # old runs
    # To collect the comparable outputs (see below), you need to run the comparable models in /comparables. 
    # "scVI":"run_crossval_n_latent_dims-50_n_layers-2_n_hidden-132_gene_likelihood-zinb_dispersion-gene_scaling-min_max_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_model_type-ae_n_components-2_2025-06-01_18-12",
    # "scANVI":"run_crossval_n_latent_dims-50_n_layers-2_n_hidden-132_gene_likelihood-zinb_dispersion-gene_scaling-min_max_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_model_type-ae_2025-06-14_17-48",
    # "scanorama":"run_crossval_n_latent_dims-50_scaling-min_max_sample_size-10000_model_type-ae_2025-06-15_21-02",
    # "harmony":"run_crossval_n_latent_dims-50_scaling-min_max_sample_size-10000_model_type-ae_2025-06-17_13-32",
    # "SAUCIE":"run_crossval_n_latent_dims-50_layers-512-132-50_lambda_b-0.0_lambda_c-0.0_lambda_d-0.0_learning_rate-0.0_scaling-min_max_batch_size-512_epochs-50_patience-30_sample_size-10000_model_type-ae_2025-06-26_12-46",
    # new runs
    "scVI":"run_crossval_n_latent_dims-50_n_layers-2_n_hidden-132_gene_likelihood-zinb_dispersion-gene_scaling-min_max_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_model_type-ae_2025-07-16_23-16",
    "scANVI":"run_crossval_n_latent_dims-50_n_layers-2_n_hidden-132_gene_likelihood-zinb_dispersion-gene_scaling-min_max_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_model_type-ae_2025-07-16_23-26",
    "scanorama":"run_crossval_n_latent_dims-50_scaling-min_max_sample_size-10000_model_type-ae_2025-07-16_23-33",
    "harmony":"run_crossval_n_latent_dims-50_scaling-min_max_sample_size-10000_model_type-ae_2025-07-16_23-39",
    "SAUCIE":"run_crossval_n_latent_dims-50_layers-512-132-50_lambda_b-0.0_lambda_c-0.0_lambda_d-0.0_learning_rate-0.0_scaling-min_max_batch_size-512_epochs-50_patience-30_sample_size-10000_model_type-ae_2025-07-17_00-36",
        }

model_paths = {k:os.path.join(ASD_OUTPUTS_DIR, "latent_space", ASD_EXPERIMENT_NAME,k, v) for k, v in model_folder_dict.items()}

Loading outputs from /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/ASD. Please verify that your models output folder is located here before proceeding with the analysis.

##### Step 1: Import the analysis class and initialize it

In [3]:

import analysis.analysis as aa

analysis_name = "ASD_default_500"



asd = aa.ASDAnalysis(model_folder_dict, analysis_name)

##### Step 2: Compile clustering scores calculated after training the models

In [4]:


res= asd.clustering_scores(model_folder_dict)
# You can now inspect or export `clustering_results` as needed
# Note: if you only run 1 fold, you will see NAN in CI entries
res

[WARN] scVI: config.json not found: /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/ASD/saved_models/log_transformed_2916hvggenes/scVI/run_crossval_n_latent_dims-50_n_layers-2_n_hidden-132_gene_likelihood-zinb_dispersion-gene_scaling-min_max_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_model_type-ae_2025-07-16_23-16/configs.json  using single-model format (AE will default to PCA format if present)
[WARN] scANVI: config.json not found: /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/ASD/saved_models/log_transformed_2916hvggenes/scANVI/run_crossval_n_latent_dims-50_n_layers-2_n_hidden-132_gene_likelihood-zinb_dispersion-gene_scaling-min_max_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_model_type-ae_2025-07-16_23-26/configs.json  using single-model format (AE will default to PCA format if present)
[WARN] scanorama: config.json not found: /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/ASD/saved_models/log_transformed_2916hvggenes/scanorama/run_crossval_n_latent_dims-50_scaling-min_max_sample_size-10000_model_type-ae_2025-07-16_23-33/configs.json  using single-model format (AE will default to PCA format if present)
[WARN] harmony: config.json not found: /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/ASD/saved_models/log_transformed_2916hvggenes/harmony/run_crossval_n_latent_dims-50_scaling-min_max_sample_size-10000_model_type-ae_2025-07-16_23-39/configs.json  using single-model format (AE will default to PCA format if present)
[WARN] SAUCIE: config.json not found: /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/ASD/saved_models/log_transformed_2916hvggenes/SAUCIE/run_crossval_n_latent_dims-50_layers-512-132-50_lambda_b-0.0_lambda_c-0.0_lambda_d-0.0_learning_rate-0.0_scaling-min_max_batch_size-512_epochs-50_patience-30_sample_size-10000_model_type-ae_2025-07-17_00-36/configs.json  using single-model format (AE will default to PCA format if present)
Directory created or already exists: /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/ASD/compare_models/log_transformed_2916hvggenes/ASD_default_500

Computed aggregated scores DataFrame
Computed Confidence interval results for sample size: 10000, saved to: /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/ASD/compare_models/log_transformed_2916hvggenes/ASD_default_500

               batch                                                        \
                1/db                       ch                   silhouette
                mean CI_lower CI_upper   mean CI_lower CI_upper       mean
dataset_type
X_pca_test      0.09     0.09     0.10  25.74    25.16    26.33      -0.09
ae_latent_test  0.09     0.09     0.10  24.67    24.05    25.29      -0.10
SAUCIE          0.08     0.08     0.08  12.49     7.76    17.22      -0.18
aec             0.06     0.05     0.07  18.46    12.89    24.03      -0.17
harmony         0.07     0.04     0.10  18.38     8.73    28.04      -0.09
scANVI          0.06     0.06     0.07  15.56    14.67    16.46      -0.15
scVI            0.06     0.05     0.06  11.83    10.97    12.69      -0.15
scanorama       0.08     0.05     0.10  20.37    12.96    27.78      -0.12
scmedalfe       0.09     0.08     0.09  13.87    10.52    17.21      -0.05
scmedalfec      0.08     0.08     0.09  16.88    15.71    18.05      -0.08
scmedalre       0.22     0.20     0.24  80.93    45.70   116.16      -0.02

                                 celltype                                      \
                                     1/db                         ch
               CI_lower CI_upper     mean CI_lower CI_upper     mean CI_lower
dataset_type
X_pca_test        -0.10    -0.09     0.46     0.45     0.47  1440.09  1427.94
ae_latent_test    -0.11    -0.09     0.44     0.43     0.44  1523.30  1432.99
SAUCIE            -0.21    -0.15     0.45     0.41     0.48  1716.57  1295.78
aec               -0.21    -0.14     0.67     0.65     0.70  5739.65  4529.05
harmony           -0.10    -0.09     0.45     0.43     0.46  1479.23  1393.49
scANVI            -0.15    -0.14     1.13     1.05     1.21  6512.85  5885.91
scVI              -0.17    -0.13     0.43     0.39     0.46  4518.33  4303.85
scanorama         -0.15    -0.08     0.43     0.39     0.47  2136.42  1163.33
scmedalfe         -0.07    -0.03     0.37     0.34     0.39   709.87   486.10
scmedalfec        -0.09    -0.07     0.37     0.36     0.37  1023.36   959.74
scmedalre         -0.04     0.00     0.32     0.29     0.35   641.18   509.68


                        silhouette
               CI_upper       mean CI_lower CI_upper
dataset_type
X_pca_test      1452.23       0.20     0.20     0.21
ae_latent_test  1613.62       0.20     0.19     0.21
SAUCIE          2137.35       0.11     0.06     0.15
aec             6950.24       0.32     0.29     0.35
harmony         1564.98       0.20     0.20     0.21
scANVI          7139.78       0.50     0.48     0.52
scVI            4732.81       0.34     0.33     0.34
scanorama       3109.51       0.26     0.18     0.33
scmedalfe        933.64       0.14     0.11     0.17
scmedalfec      1086.99       0.17     0.16     0.18
scmedalre        772.68       0.12     0.10     0.14

##### Step 3: Generate and save the UMAP plots

In [5]:

# This typically loads latent representations stored after training and creates UMAPs for each model
processors = asd.umap(model_folder_dict, types=["train"], splits=[1])
processors

\plot configs dict_items([('markers', ['x', '+', '<', 'h', 's', '.', 'o', 's', '^', '*', '1', '8', 'p', 'P', 'D', '|', 0, ',', 'd', 2]), ('palette_choice', ['#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#000000', '#fabebe', '#008080', '#e6beff', '#9a6324', '#d2f53c', '#7fff00', '#000080', '#800000', '#808000', '#800080', '#808080', '#ffd700', '#ff4500', '#00ff7f', '#dda0dd', '#87ceeb', '#00ced1', '#9400d3', '#ff6347', '#4682b4', '#6b8e23', '#a52a2a']), ('showplot', False), ('save_fig', True), ('outpath', None), ('use_bio_bio', True), ('use_batch_batch', True), ('use_bio_batch', False), ('use_batch_bio', False)])

df_latent columns: Index(['Key', 'Split', 'LatentPath', 'Type'], dtype='object')
df_latent:
         Key  Split                                         LatentPath   Type
0        ae      1  /archive/bioinformatics/DLLab/AixaAndrade/src/...  train
1        ae      1  /archive/bioinformatics/DLLab/AixaAndrade/src/...    val
2        ae      1  /archive/bioinformatics/DLLab/AixaAndrade/src/...   test
3        ae      2  /archive/bioinformatics/DLLab/AixaAndrade/src/...  train
4        ae      2  /archive/bioinformatics/DLLab/AixaAndrade/src/...    val
..      ...    ...                                                ...    ...
145  SAUCIE      4  /archive/bioinformatics/DLLab/AixaAndrade/src/...    val
146  SAUCIE      4  /archive/bioinformatics/DLLab/AixaAndrade/src/...   test
147  SAUCIE      5  /archive/bioinformatics/DLLab/AixaAndrade/src/...  train
148  SAUCIE      5  /archive/bioinformatics/DLLab/AixaAndrade/src/...    val
149  SAUCIE      5  /archive/bioinformatics/DLLab/AixaAndrade/src/...   test

[150 rows x 4 columns]

df_inputs columns: Index(['Split', 'Type', 'InputsPath'], dtype='object')
df_inputs:
    Split   Type                                         InputsPath
0      1  train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
1      1    val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
2      2  train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
3      2    val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
4      3  train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
5      3    val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
6      4  train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
7      4    val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
8      5  train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
9      5    val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
Reading paths, df head:
   Key  Split                                         LatentPath   Type  \
0  ae      1  /archive/bioinformatics/DLLab/AixaAndrade/src/...  train
1  ae      1  /archive/bioinformatics/DLLab/AixaAndrade/src/...    val
2  ae      1  /archive/bioinformatics/DLLab/AixaAndrade/src/...   test
3  ae      2  /archive/bioinformatics/DLLab/AixaAndrade/src/...  train
4  ae      2  /archive/bioinformatics/DLLab/AixaAndrade/src/...    val

                                          InputsPath      latent_prefix  \
0  /archive/bioinformatics/DLLab/AixaAndrade/src/...  ae_latent_train_1
1  /archive/bioinformatics/DLLab/AixaAndrade/src/...    ae_latent_val_1
2                                                NaN   ae_latent_test_1
3  /archive/bioinformatics/DLLab/AixaAndrade/src/...  ae_latent_train_2
4  /archive/bioinformatics/DLLab/AixaAndrade/src/...    ae_latent_val_2

  input_prefix
0      train_1
1        val_1
2       test_1
3      train_2
4        val_2
Computing UMAP projections...
Index(['Key', 'Split', 'LatentPath', 'Type', 'InputsPath', 'latent_prefix',
       'input_prefix'],
      dtype='object')


Processing prefix: 0 train_1
Reading data from: /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/scMEDAL_for_scRNAseq/Experiments/data/ASD_data/reverse_norm/log_transformed_2916hvggenes/splits/split_1/train

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 62735 cells × 2916 features, using 'X_pca'
UMAP shape: (62735, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 62735 cells × 50 features, using 'X'
UMAP shape: (62735, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 62735 cells × 50 features, using 'X'
UMAP shape: (62735, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 62735 cells × 50 features, using 'X'
UMAP shape: (62735, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 62735 cells × 50 features, using 'X'
UMAP shape: (62735, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 62735 cells × 50 features, using 'X'
UMAP shape: (62735, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 62735 cells × 50 features, using 'X'
UMAP shape: (62735, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 62735 cells × 50 features, using 'X'
UMAP shape: (62735, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 62735 cells × 50 features, using 'X'

##### Step 4: Run genomaps on a subsample of the input data along with reconstructions from the scmedalfe and scmedalre models. 

Visualize selected batches to assess batch-specific effects in the reconstructed spaces, including conterfactual projections from scmedalre.

In [ ]:
# Run genomaps on a subsample input+scmedalfe recon +scmedal re recon for different batches
dict_batches = {
    "donor_5531": "ASD",
    "donor_5945": "ASD",
    "donor_5419": "ASD",
    "donor_6032": "control",
    "donor_5242": "control",
    "donor_5976": "control",
}
print("dict_batches:", dict_batches)

batches = [
    "donor_5531",
    "donor_5945",
    "donor_5419",
    "donor_6032",
    "donor_5242",
    "donor_5976",
]
# for this genomap config, you need to compute first the reconstructions from scMEDAL-FE and scMEDAL-RE
selected_models = {k: model_folder_dict[k] for k in ("scmedalfe", "scmedalre")}
gfd = asd.genomap(selected_models,
                            n_batches = 31,
                            num_iter = 100, # for quick test, otherwise 100
                            cell_id_col = "cell",
                            gene_index_col = "gene_ids",
                            celltype = ["L2/3"],
                            batches=batches,
                            models=['scmedalre'],#if add_inputs_fe=True-> scmedalfe+ inputs are used for genomap creation by default, no need to add the to the list, 
                            types=["train"], 
                            splits=[1],
                            add_inputs_fe= True,
                            extra_recon = "fe",
                            min_val = -2,
                            max_val = 6 )

dict_batches: {'donor_5531': 'ASD', 'donor_5945': 'ASD', 'donor_5419': 'ASD', 'donor_6032': 'control', 'donor_5242': 'control', 'donor_5976': 'control'}

Looking for outputs paths for the following models:dict_keys(['scmedalfe', 'scmedalre'])
Created df with input and recon paths
           Key  Split                                          ReconPath  \
0    scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
1    scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
2    scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
3    scmedalfe      2  /endosome/archive/bioinformatics/DLLab/src/Aix...
4    scmedalfe      2  /endosome/archive/bioinformatics/DLLab/src/Aix...
..         ...    ...                                                ...
490  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
491  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
492  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
493  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
494  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...

      Type                                         InputsPath  \
0    train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
1      val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
2     test                                                NaN
3    train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
4      val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
..     ...                                                ...
490   test                                                NaN
491   test                                                NaN
492   test                                                NaN
493   test                                                NaN
494   test                                                NaN

                    recon_prefix
0                    recon_train
1                      recon_val
2                     recon_test
3                    recon_train
4                      recon_val
..                           ...
490  recon_batch_test_donor_5278
491  recon_batch_test_donor_5408
492  recon_batch_test_donor_5841
493  recon_batch_test_donor_1823
494  recon_batch_test_donor_5419

[495 rows x 6 columns]


Initialized genomap pipeline
sparse False
Computing genomap for ['train'] [1] ['scmedalre']
train 1 scmedalre
Searching input paths in df
           Key  Split                                          ReconPath  \
0    scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
1    scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
2    scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
3    scmedalfe      2  /endosome/archive/bioinformatics/DLLab/src/Aix...
4    scmedalfe      2  /endosome/archive/bioinformatics/DLLab/src/Aix...
..         ...    ...                                                ...
490  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
491  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
492  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
493  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
494  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...

      Type                                         InputsPath  \
0    train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
1      val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
2     test                                                NaN
3    train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
4      val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
..     ...                                                ...
490   test                                                NaN
491   test                                                NaN
492   test                                                NaN
493   test                                                NaN
494   test                                                NaN

                    recon_prefix
0                    recon_train
1                      recon_val
2                     recon_test
3                    recon_train
4                      recon_val
..                           ...
490  recon_batch_test_donor_5278
491  recon_batch_test_donor_5408
492  recon_batch_test_donor_5841
493  recon_batch_test_donor_1823
494  recon_batch_test_donor_5419

[495 rows x 6 columns]
Searching input paths in df
           Key  Split                                          ReconPath  \
0    scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
1    scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
2    scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
3    scmedalfe      2  /endosome/archive/bioinformatics/DLLab/src/Aix...
4    scmedalfe      2  /endosome/archive/bioinformatics/DLLab/src/Aix...
..         ...    ...                                                ...
490  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
491  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
492  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
493  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
494  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...

      Type                                         InputsPath  \
0    train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
1      val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
2     test                                                NaN
3    train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
4      val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
..     ...                                                ...
490   test                                                NaN
491   test                                                NaN
492   test                                                NaN
493   test                                                NaN
494   test                                                NaN

                    recon_prefix
0                    recon_train
1                      recon_val
2                     recon_test
3                    recon_train
4                      recon_val
..                           ...
490  recon_batch_test_donor_5278
491  recon_batch_test_donor_5408
492  recon_batch_test_donor_5841
493  recon_batch_test_donor_1823
494  recon_batch_test_donor_5419

[495 rows x 6 columns]
Reading data from: /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/scMEDAL_for_scRNAseq/Experiments/data/ASD_data/reverse_norm/log_transformed_2916hvggenes/splits/split_1/train
batch_sel ['donor_5531', 'donor_5945', 'donor_5419', 'donor_6032', 'donor_5242', 'donor_5976']
Selected 1 cell from batch donor_5531 with celltype L2/3.
Selected 1 cell from batch donor_5945 with celltype L2/3.
Selected 1 cell from batch donor_5419 with celltype L2/3.
Selected 1 cell from batch donor_6032 with celltype L2/3.
Selected 1 cell from batch donor_5242 with celltype L2/3.
Selected 1 cell from batch donor_5976 with celltype L2/3.
Selected 294 additional cells from specified celltypes.
input_train
Reading data from: /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/scMEDAL_for_scRNAseq/Experiments/data/ASD_data/reverse_norm/log_transformed_2916hvggenes/splits/split_1/train
fe_ae_recon_train
recon_train
recon_batch_train_donor_5242
recon_batch_train_donor_1823
recon_batch_train_donor_5419
recon_batch_train_donor_5391
recon_batch_train_donor_4849
recon_batch_train_donor_5294
recon_batch_train_donor_5864
recon_batch_train_donor_6032
recon_batch_train_donor_5976
recon_batch_train_donor_5945
recon_batch_train_donor_5841
recon_batch_train_donor_5879
recon_batch_train_donor_4899
recon_batch_train_donor_5939
recon_batch_train_donor_5531
recon_batch_train_donor_5278
recon_batch_train_donor_5893
recon_batch_train_donor_5408
recon_batch_train_donor_5403
recon_batch_train_donor_5936
recon_batch_train_donor_5978
recon_batch_train_donor_5565
recon_batch_train_donor_5144
recon_batch_train_donor_4341
recon_batch_train_donor_5577
recon_batch_train_donor_5387
recon_batch_train_donor_5538
recon_batch_train_donor_5163
recon_batch_train_donor_5554
recon_batch_train_donor_6033
Shape of concatenated x: (9900, 2916)
Shape of concatenated obs: (9900, 24)
created folder path: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/ASD/compare_models/log_transformed_2916hvggenes/ASD_default_500/CMmultibatch_300_cells_per_batch_31batches_L23_with_2fe_input
Folder already exists: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/ASD/compare_models/log_transformed_2916hvggenes/ASD_default_500/CMmultibatch_300_cells_per_batch_31batches_L23_with_2fe_input

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

batches 2 select from ['donor_5531', 'donor_5945', 'donor_5419', 'donor_6032', 'donor_5242', 'donor_5976']
TCGCGAGAGACATAAC-1_5531_BA24 comes from batch donor_5531
TCACAAGTCTGCTTGC-1_5945_PFC comes from batch donor_5945
TTCTACATCACCGGGT-1_5419_PFC comes from batch donor_5419
ACCGTAACAAGGACAC-1_6032_BA24 comes from batch donor_6032
CATTCGCCAAGCTGGA-1_5242_BA24 comes from batch donor_5242
GGAAAGCAGAAGGACA-1_5976_BA9 comes from batch donor_5976
original batch list: ['donor_5531', 'donor_5945', 'donor_5419', 'donor_6032', 'donor_5242', 'donor_5976']
Reading data from: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/ASD/compare_models/log_transformed_2916hvggenes/ASD_default_500/CMmultibatch_300_cells_per_batch_31batches_L23_with_2fe_input

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Input does not contain NaNs
subset_input_z_scores shape: (9900, 2916)

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:261: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.1, 1, 1])  # Adjust layout to make room for colorbar

Missing indices: set()
n cell indexes Index([ 125,  425,  725, 1025, 1325, 1625, 1925, 2225, 2525, 2825, 3125, 3425,
       3725, 4025, 4325, 4625, 4925, 5225, 5525, 5825, 6125, 6425, 6725, 7025,
       7325, 7625, 7925, 8225, 8525, 8825, 9125, 9425, 9725],
      dtype='int64')
Shape of std_across_batches: (54, 54)


plotting big panel for TCGCGAGAGACATAAC-1_5531_BA24 with original batch donor_5531 and celltype L2/3, n recons: 33

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([125, 425, 1025, 1625, 3125, 3425, 3725, 5225], dtype='int64')
plotting small panel for TCGCGAGAGACATAAC-1_5531_BA24 with original batch donor_5531 and celltype L2/3, n recons: 8

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([   1,  301,  601,  901, 1201, 1501, 1801, 2101, 2401, 2701, 3001, 3301,
       3601, 3901, 4201, 4501, 4801, 5101, 5401, 5701, 6001, 6301, 6601, 6901,
       7201, 7501, 7801, 8101, 8401, 8701, 9001, 9301, 9601],
      dtype='int64')
Shape of std_across_batches: (54, 54)


plotting big panel for TCACAAGTCTGCTTGC-1_5945_PFC with original batch donor_5945 and celltype L2/3, n recons: 33

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([1, 301, 901, 1501, 3001, 3301, 3601, 5101], dtype='int64')
plotting small panel for TCACAAGTCTGCTTGC-1_5945_PFC with original batch donor_5945 and celltype L2/3, n recons: 8

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([  83,  383,  683,  983, 1283, 1583, 1883, 2183, 2483, 2783, 3083, 3383,
       3683, 3983, 4283, 4583, 4883, 5183, 5483, 5783, 6083, 6383, 6683, 6983,
       7283, 7583, 7883, 8183, 8483, 8783, 9083, 9383, 9683],
      dtype='int64')
Shape of std_across_batches: (54, 54)


plotting big panel for TTCTACATCACCGGGT-1_5419_PFC with original batch donor_5419 and celltype L2/3, n recons: 33

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([83, 383, 983, 1583, 3083, 3383, 3683, 5183], dtype='int64')
plotting small panel for TTCTACATCACCGGGT-1_5419_PFC with original batch donor_5419 and celltype L2/3, n recons: 8

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([   3,  303,  603,  903, 1203, 1503, 1803, 2103, 2403, 2703, 3003, 3303,
       3603, 3903, 4203, 4503, 4803, 5103, 5403, 5703, 6003, 6303, 6603, 6903,
       7203, 7503, 7803, 8103, 8403, 8703, 9003, 9303, 9603],
      dtype='int64')
Shape of std_across_batches: (54, 54)


plotting big panel for ACCGTAACAAGGACAC-1_6032_BA24 with original batch donor_6032 and celltype L2/3, n recons: 33

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([3, 303, 903, 1503, 3003, 3303, 3603, 5103], dtype='int64')
plotting small panel for ACCGTAACAAGGACAC-1_6032_BA24 with original batch donor_6032 and celltype L2/3, n recons: 8

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([ 141,  441,  741, 1041, 1341, 1641, 1941, 2241, 2541, 2841, 3141, 3441,
       3741, 4041, 4341, 4641, 4941, 5241, 5541, 5841, 6141, 6441, 6741, 7041,
       7341, 7641, 7941, 8241, 8541, 8841, 9141, 9441, 9741],
      dtype='int64')
Shape of std_across_batches: (54, 54)


plotting big panel for CATTCGCCAAGCTGGA-1_5242_BA24 with original batch donor_5242 and celltype L2/3, n recons: 33

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([141, 441, 1041, 1641, 3141, 3441, 3741, 5241], dtype='int64')
plotting small panel for CATTCGCCAAGCTGGA-1_5242_BA24 with original batch donor_5242 and celltype L2/3, n recons: 8

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([   5,  305,  605,  905, 1205, 1505, 1805, 2105, 2405, 2705, 3005, 3305,
       3605, 3905, 4205, 4505, 4805, 5105, 5405, 5705, 6005, 6305, 6605, 6905,
       7205, 7505, 7805, 8105, 8405, 8705, 9005, 9305, 9605],
      dtype='int64')
Shape of std_across_batches: (54, 54)


plotting big panel for GGAAAGCAGAAGGACA-1_5976_BA9 with original batch donor_5976 and celltype L2/3, n recons: 33

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([5, 305, 905, 1505, 3005, 3305, 3605, 5105], dtype='int64')
plotting small panel for GGAAAGCAGAAGGACA-1_5976_BA9 with original batch donor_5976 and celltype L2/3, n recons: 8

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels

## Run the Mixed Effects Classifier (MEC) on latent spaces generated by scmedalfe and scmedalre.

Classification target: 2 patient groups (e.g., ASD vs. Control)

$python\ mec\_asd.py$

In [ ]:
# Now get a summary table of all mec results
from utils.compare_results_utils import get_all_mec_metrics
df,_ = get_all_mec_metrics(ASD_OUTPUTS_DIR,ASD_EXPERIMENT_NAME, split='test')
df

MEC RF summary able saved to /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/ASD/latent_space/log_transformed_2916hvggenes/mec/MEC_RF_summary.csv

,latent,RFAccuracy_mean,RFAccuracy_95CI_lower,RFAccuracy_95CI_upper,RFBalancedAccuracy_mean,RFBalancedAccuracy_95CI_lower,RFBalancedAccuracy_95CI_upper,ChanceAccuracy_mean,ChanceAccuracy_95CI_lower,ChanceAccuracy_95CI_upper,run_name
0,scVI_latent,63.21,62.62,63.80,63.20,62.62,63.79,50.06,49.75,50.37,scVI_latent_n_pred-2_bio_col-diagnosis_2025-07...
0,scmedalfec_latent,66.84,65.58,68.11,66.85,65.59,68.11,50.06,49.75,50.37,scmedalfec_latent_n_pred-2_bio_col-diagnosis_2...
0,scmedalfe_latent,67.44,66.39,68.49,67.45,66.40,68.49,50.06,49.75,50.37,scmedalfe_latent_n_pred-2_bio_col-diagnosis_20...
0,X_pca,73.04,72.46,73.62,73.05,72.47,73.63,50.06,49.75,50.37,X_pca_n_pred-2_bio_col-diagnosis_2025-07-16_12-13
0,scmedalfec_latent_re_latent-scmedalre_latent,90.02,86.19,93.84,90.02,86.20,93.84,50.06,49.75,50.37,scmedalfec_latent_re_latent-scmedalre_latent_n...
0,scmedalfe_latent_re_latent-scmedalre_latent,90.04,86.46,93.61,90.04,86.47,93.61,50.06,49.75,50.37,scmedalfe_latent_re_latent-scmedalre_latent_n_...
0,X_pca_re_latent-scmedalre_latent,90.22,86.71,93.73,90.22,86.71,93.73,50.06,49.75,50.37,X_pca_re_latent-scmedalre_latent_n_pred-2_bio_...