In [1]:
#Notebook Runned with Aixa_ARMED nev
#This notebook was created to split th data in train, test and val for seen data (for Leukemia dataset all data is seen)

import anndata
import sys


sys.path.append("/archive/bioinformatics/DLLab/AixaAndrade/src/ARMED_genomics/utils")
from utils import read_adata
from splitter import DataSplitter
from config_split_paths import data_path,data2split_foldername,folder_splits
import numpy as np

In [2]:
adata2split_path = data_path + "/" + data2split_foldername
print(adata2split_path)
X,var,obs = read_adata(adata2split_path, issparse=True)
#adata = anndata.AnnData(X,obs=obs,var=var)
#print("adata shape",adata.shape)

/archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes

In [3]:
#X = loaded_X.item()
adata = anndata.AnnData(X,obs=obs,var=var)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/Aixa_ARMED_2/lib/python3.8/site-packages/anndata/_core/anndata.py:119: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

In [4]:
adata.obs

,Unnamed: 0,Age,AgeBin,DeathType,DonorID,Gender,Organ,Race,SampleType,Source,Tissue,TissueDetail,_index,celltype,protocol,sampleID,n_genes
0,0,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCAAGAACGCGT-1-H0015_apex',Smooth_muscle_cells,10X3'V3,H0015_apex,480
1,1,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCAAGCAAACAT-1-H0015_apex',Ventricular_Cardiomyocyte,10X3'V3,H0015_apex,1365
2,2,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCAAGCTACTGT-1-H0015_apex',Ventricular_Cardiomyocyte,10X3'V3,H0015_apex,1521
3,3,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCAGTACCGCGT-1-H0015_apex',Pericytes,10X3'V3,H0015_apex,726
4,4,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCATCAAACCCA-1-H0015_apex',Ventricular_Cardiomyocyte,10X3'V3,H0015_apex,1584
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486129,486129,NaN,60-65,DCD(circulatory death),D11,Female,Heart,Caucasian,normal,CD45+,AX,apex,b'TTTGTTGTCATACGGT-1-HCAHeart8102862',Endothelial,10X3'V3,HCAHeart8102862,904
486130,486130,NaN,60-65,DCD(circulatory death),D11,Female,Heart,Caucasian,normal,CD45+,AX,apex,b'TTTGTTGTCCTACCAC-1-HCAHeart8102862',Endothelial,10X3'V3,HCAHeart8102862,692
486131,486131,NaN,60-65,DCD(circulatory death),D11,Female,Heart,Caucasian,normal,CD45+,AX,apex,b'TTTGTTGTCGACGCTG-1-HCAHeart8102862',Endothelial,10X3'V3,HCAHeart8102862,847
486132,486132,NaN,60-65,DCD(circulatory death),D11,Female,Heart,Caucasian,normal,CD45+,AX,apex,b'TTTGTTGTCGGCTGAC-1-HCAHeart8102862',Endothelial,10X3'V3,HCAHeart8102862,1925
486133,486133,NaN,60-65,DCD(circulatory death),D11,Female,Heart,Caucasian,normal,CD45+,AX,apex,b'TTTGTTGTCGGTGTTA-1-HCAHeart8102862',Endothelial,10X3'V3,HCAHeart8102862,1422

In [5]:
len(np.unique(adata.obs["sampleID"]))

147

In [6]:
adata.obs["sampleID"]

0              H0015_apex
1              H0015_apex
2              H0015_apex
3              H0015_apex
4              H0015_apex
               ...
486129    HCAHeart8102862
486130    HCAHeart8102862
486131    HCAHeart8102862
486132    HCAHeart8102862
486133    HCAHeart8102862
Name: sampleID, Length: 486134, dtype: object

In [7]:
adata.obs['celltype'] = adata.obs['celltype'].astype('category')
# adata.obs['donor'] = adata.obs['individual'].astype('str')
# adata.obs['donor'] =['donor-'+str(d) for d in adata.obs['donor']]
adata.obs['batch'] = adata.obs["sampleID"].astype('category')

In [8]:
#Check data to split
print("count matrix shape:",adata.shape)
#adata.obs["celltype"] = adata.obs["CellType"]

print("n cell types:",len(np.unique(adata.obs["celltype"])))
print("cell types:",np.unique(adata.obs["celltype"]))
#adata.obs["donor"] = adata.obs["id"]
print("\nn batches:",len(np.unique(adata.obs["batch"])))
print("batches:",np.unique(adata.obs["batch"]))

count matrix shape: (486134, 3000)
n cell types: 13
cell types: ['Adipocytes' 'Atrial_Cardiomyocyte' 'Endothelial' 'Fibroblast' 'Lymphoid'
 'Mesothelial' 'Myeloid' 'Neuronal' 'NotAssigned' 'Pericytes'
 'Smooth_muscle_cells' 'Ventricular_Cardiomyocyte' 'doublets']

n batches: 147
batches: ['H0015_LA_new' 'H0015_LV' 'H0015_RA' 'H0015_RV' 'H0015_apex'
 'H0015_septum' 'H0020_LA_new' 'H0020_LV' 'H0020_RA' 'H0020_RV'
 'H0020_apex' 'H0020_septum' 'H0025_LA' 'H0025_LV' 'H0025_RA' 'H0025_RV'
 'H0025_apex' 'H0025_septum' 'H0026_LA' 'H0026_LV_V3' 'H0026_RA'
 'H0026_RV' 'H0026_apex' 'H0026_septum2' 'H0035_LA' 'H0035_LV' 'H0035_RA'
 'H0035_RV' 'H0035_apex' 'H0035_septum' 'H0037_Apex' 'H0037_LA_corr'
 'H0037_LV' 'H0037_RA_corr' 'H0037_RV' 'H0037_septum' 'HCAHeart7606896'
 'HCAHeart7656534' 'HCAHeart7656535' 'HCAHeart7656536' 'HCAHeart7656537'
 'HCAHeart7656538' 'HCAHeart7656539' 'HCAHeart7664652' 'HCAHeart7664653'
 'HCAHeart7664654' 'HCAHeart7698015' 'HCAHeart7698016' 'HCAHeart7698017'
 'HCAHeart7702873' 'HCAHeart7702874' 'HCAHeart7702875' 'HCAHeart7702876'
 'HCAHeart7702877' 'HCAHeart7702878' 'HCAHeart7702879' 'HCAHeart7702880'
 'HCAHeart7702881' 'HCAHeart7702882' 'HCAHeart7728604' 'HCAHeart7728605'
 'HCAHeart7728606' 'HCAHeart7728607' 'HCAHeart7728608' 'HCAHeart7728609'
 'HCAHeart7745966' 'HCAHeart7745967' 'HCAHeart7745968' 'HCAHeart7745969'
 'HCAHeart7745970' 'HCAHeart7751845' 'HCAHeart7757636' 'HCAHeart7757637'
 'HCAHeart7757638' 'HCAHeart7757639' 'HCAHeart7829976' 'HCAHeart7829977'
 'HCAHeart7829978' 'HCAHeart7829979' 'HCAHeart7833852' 'HCAHeart7833853'
 'HCAHeart7833854' 'HCAHeart7833855' 'HCAHeart7835148' 'HCAHeart7835149'
 'HCAHeart7836681' 'HCAHeart7836682' 'HCAHeart7836683' 'HCAHeart7836684'
 'HCAHeart7843999' 'HCAHeart7844000' 'HCAHeart7844001' 'HCAHeart7844002'
 'HCAHeart7844003' 'HCAHeart7844004' 'HCAHeart7850539' 'HCAHeart7850540'
 'HCAHeart7850541' 'HCAHeart7850542' 'HCAHeart7850543' 'HCAHeart7850544'
 'HCAHeart7850545' 'HCAHeart7850546' 'HCAHeart7850547' 'HCAHeart7850548'
 'HCAHeart7850549' 'HCAHeart7850551' 'HCAHeart7880860' 'HCAHeart7880861'
 'HCAHeart7880862' 'HCAHeart7880863' 'HCAHeart7888922' 'HCAHeart7888923'
 'HCAHeart7888924' 'HCAHeart7888925' 'HCAHeart7888926' 'HCAHeart7888927'
 'HCAHeart7888928' 'HCAHeart7888929' 'HCAHeart7905327' 'HCAHeart7905328'
 'HCAHeart7905329' 'HCAHeart7905330' 'HCAHeart7905331' 'HCAHeart7905332'
 'HCAHeart7964513' 'HCAHeart7985086' 'HCAHeart7985087' 'HCAHeart7985088'
 'HCAHeart7985089' 'HCAHeart8102858' 'HCAHeart8102859' 'HCAHeart8102860'
 'HCAHeart8102861' 'HCAHeart8102862' 'HCAHeart8102863' 'HCAHeart8102864'
 'HCAHeart8102865' 'HCAHeart8102866' 'HCAHeart8102867' 'HCAHeart8102868'
 'HCAHeart8287123' 'HCAHeart8287124' 'HCAHeart8287125' 'HCAHeart8287126'
 'HCAHeart8287127' 'HCAHeart8287128']

In [9]:
adata.var

,Unnamed: 0,_index,gene_ids,n_cells,highly_variable,means,dispersions,dispersions_norm
0,5,b'AL627309.2',b'ENSG00000239906',11,True,0.000101,2.430229,1.432752
1,7,b'AL732372.1',b'ENSG00000236601',6,True,0.000108,2.301117,1.012375
2,19,b'AL645608.1',b'ENSG00000223764',901,True,0.011911,2.308639,1.036867
3,20,b'SAMD11',b'ENSG00000187634',4056,True,0.047151,2.298307,1.003227
4,26,b'HES4',b'ENSG00000188290',95117,True,0.942373,2.632907,0.875079
...,...,...,...,...,...,...,...,...
2995,33494,b'S100B',b'ENSG00000160307',2761,True,0.052005,3.101684,3.618944
2996,33497,b'MT-ND2',b'ENSG00000198763',176135,True,2.562359,3.970598,1.051245
2997,33499,b'MT-CO2',b'ENSG00000198712',245109,True,3.264734,4.525665,1.025560
2998,33505,b'MT-ND4',b'ENSG00000198886',208143,True,3.113622,4.532405,1.050785
2999,33513,b'AC136616.2',b'ENSG00000277761',7,True,0.000113,2.311633,1.046614

In [10]:
adata.obs.head(5)

,Unnamed: 0,Age,AgeBin,DeathType,DonorID,Gender,Organ,Race,SampleType,Source,Tissue,TissueDetail,_index,celltype,protocol,sampleID,n_genes,batch
0,0,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCAAGAACGCGT-1-H0015_apex',Smooth_muscle_cells,10X3'V3,H0015_apex,480,H0015_apex
1,1,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCAAGCAAACAT-1-H0015_apex',Ventricular_Cardiomyocyte,10X3'V3,H0015_apex,1365,H0015_apex
2,2,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCAAGCTACTGT-1-H0015_apex',Ventricular_Cardiomyocyte,10X3'V3,H0015_apex,1521,H0015_apex
3,3,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCAGTACCGCGT-1-H0015_apex',Pericytes,10X3'V3,H0015_apex,726,H0015_apex
4,4,NaN,50-55,DBD(brain death),H5,Female,Heart,Caucasian,Pulmonary disease,Nuclei,AX,apex,b'AAACCCATCAAACCCA-1-H0015_apex',Ventricular_Cardiomyocyte,10X3'V3,H0015_apex,1584,H0015_apex

In [11]:
# Call DataSplitter (5 folds)
splitter = DataSplitter()
# For the Leukemia datase, we will take all donors as seen
DataSplitter.Get_Kfolds_likeAlbert(adata = adata, out_folder=data_path+"/"+folder_splits, n_splits=5, stratified=True, stratify_cols=['batch','celltype'])

/archive/bioinformatics/DLLab/shared/CondaEnvironments/Aixa_ARMED_2/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"

Processing Fold 1
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_1/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_1/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_1/val

Processing Fold 2
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_2/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_2/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_2/val

Processing Fold 3
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_3/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_3/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_3/val

Processing Fold 4
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_4/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_4/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_4/val

Processing Fold 5
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_5/train
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_5/test
creating folder: /archive/bioinformatics/DLLab/AixaAndrade/data/Genomic_data/heart_data/Healthy_human_heart_data/log_transformed_3000hvggenes/splits/split_5/val

In [8]:
2

2